name: Pull Request into Master, Develop and Preprod

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'preprod'

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 23
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'yarn'

      - name: Install Node modules
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Unit & Integration tests
        run: yarn test

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Android
        run: |
          # Add your Android build commands here
          echo "Building Android app..."
          # Example: ./gradlew assembleRelease

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          APP_CENTER_TOKEN_ANDROID: ${{ secrets.APP_CENTER_TOKEN_ANDROID }}

  build-ios:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build iOS
        run: |
          # Add your iOS build commands here
          echo "Building iOS app..."
          # Example: xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphoneos -configuration Release

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          APP_CENTER_TOKEN_IOS: ${{ secrets.APP_CENTER_TOKEN_IOS }}
